export const ROLE_TO_ROUTES: Record<string, string[]> = {
  Admin: [
    "admin",
    "manager",
    "nursery-profile",
    "staff",
    "caretaker",
    "shipper",
    "categories-tags",
    "dashboard",
    "profile",
    "orders",
    "wishlist",
    "cart",
    "ai-plant-recommendation",
  ],
  Manager: [
    "manager",
    "nursery-profile",
    "staff",
    "caretaker",
    "shipper",
    "dashboard",
    "profile",
    "orders",
    "wishlist",
    "cart",
    "ai-plant-recommendation",
  ],
  Staff: [
    "staff",
    "dashboard",
    "profile",
    "orders",
    "wishlist",
    "cart",
    "ai-plant-recommendation",
  ],
  Consultant: [
    "consultant",
    "dashboard",
    "profile",
    "orders",
    "wishlist",
    "cart",
    "ai-plant-recommendation",
  ],
  Caretaker: [
    "caretaker",
    "dashboard",
    "profile",
    "orders",
    "wishlist",
    "cart",
    "ai-plant-recommendation",
  ],
  Shipper: [
    "shipper",
    "dashboard",
    "profile",
    "orders",
    "wishlist",
    "cart",
    "ai-plant-recommendation",
  ],
  Customer: [
    "services",
    "design-registration",
    "profile",
    "orders",
    "wishlist",
    "cart",
    "ai-plant-recommendation",
    "ai-chatbot",
  ],
};

const ALL_ROLES = [
  "Admin",
  "Manager",
  "Staff",
  "Consultant",
  "Caretaker",
  "Shipper",
  "Customer",
] as const;

const INTERNAL_ROLES = ALL_ROLES.filter((r) => r !== "Customer");

export const ROUTE_TO_ROLES: Record<string, string[]> = {
  admin: ["Admin"],
  manager: ["Admin", "Manager"],
  "nursery-profile": ["Admin", "Manager"],
  staff: ["Admin", "Manager", "Staff"],
  caretaker: ["Admin", "Manager", "Caretaker"],
  shipper: ["Admin", "Manager", "Shipper"],
  consultant: ["Admin", "Manager", "Staff", "Consultant"],
  services: ["Customer"],
  "design-registration": ["Customer"],
  "ai-chatbot": ["Customer"],
  dashboard: [...INTERNAL_ROLES],
  sessions: [...INTERNAL_ROLES],
  orders: [...ALL_ROLES],
  wishlist: [...ALL_ROLES],
  cart: [...ALL_ROLES],
  profile: [...ALL_ROLES],
  "ai-plant-recommendation": [...ALL_ROLES],
};
